/*!
  \file    cspy-test.mac
  \brief   C-SPY macros for testing with CTest
  \version 20230928
*/

__param testVar, testExpected;
__var breakpoint;

execUserSetup() {
  __message "-- C-SPY TEST: Loading macros";
  __var action, condition;
  action     = __smessage "messagePass(",testVar,", testExpected)";
  condition  = __smessage testVar, "==", testExpected;
  //           __setDataBreak(location, count, condition, cond_type, access, action)
  breakpoint = __setDataBreak(testVar, 0, condition, "TRUE", "W", action);

  if( !breakpoint ) {
    __message "-- C-SPY TEST: Failed to set breakpoint";
    execUserExit();
  }
}

messagePass(v1, v2) {
  __message "-- C-SPY TEST: Expected: ", v2, ". Got: ", v1, ". Result: PASS";
}

execUserExit() {
  __clearBreak( breakpoint );
  __message "-- C-SPY TEST: Unloading macros";
}
